### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by DYDARK** [ma-ku/homebridge-elero-stick#3]
Any chance to update this in regard to "Lüftungsstellung" etc?

**Comment by ma-ku** [comment]
If you could put this into context? I know that there are additional positions defined in the protocol. Unfortunately I believe they are not supported by HomeKit at least when i developed this.

```
  UP:                     0x20,
  INTERM_POS:             0x44,
  VENT_POS:               0x24,
  DOWN:                   0x40,
  STOP:                   0x10  
```

One thing that could be done is to provide additional accessories (switch) to allow moving to these positions. If this is somehow supported within the context of HomeKit Coverings, we could add this.

**Comment by DYDARK** [comment]
Thanks for your reply. Unfortunately, I am not the biggest programmer. My knowledge is quite modest.

Specifically, I want to have the shutters open, for example, to circa 7.6% (ventilation position according to Homebridge status after manual operation with the hand-held radio transmitter). The percentage display in Homekit unfortunately does not work reliably. 

Maybe a dummy switch could be used to send a command such as "open blinds to 7.6%"?

**Comment by ma-ku** [comment]
So you are working with blinds. I only have shutters and with these the math is a bit complicated. In addition, I do not get percentages from the motor. I can only measure the time the motor is running. And this becomes especially tricky since I do not get notified when the motor is started via the remote control. In wait mode I am only polling the motor status every five seconds so eventually a few seconds aka centimeters aka degrees are missing.

you can modify the times in the config file if you want to have more rigid and thus more often polling.

**Comment by DYDARK** [comment]
Thank you! I had already tried that, but unfortunately I did not come to a happy solution with it.

Is there a command I could start via http, for example something like "set blinds to 7.5%" or "blinds up for 3 seconds"?

Many greetings

**Comment by DYDARK** [comment]
I have solved my problem:

With the Eve app I created two scenes ("blind up" and "blind stop"); then I created an automation in the Home app with both scenes, which I converted into a shortcut; between the first scene ("blind up") and the second scene ("blind stop") I inserted a few seconds pause (2 seconds), so that the blind can go into the ventilation position. 

Unfortunately, the Home app does not allow so many options (especially the command "blind stop"), so the little detour via the Eve app.

Thanks for the quick reply and best regards.
